name: Common Steps

on: [workflow_call]

jobs:
  common-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd angular-extend && npm install

      - name: Run ESLint with fix
        run: cd angular-extend && npm run lint:fix

      - name: Run tests
        run: cd angular-extend && npm run test

      - name: Run linter
        run: cd angular-extend && npm run lint