name: Development Workflow

on:
  push:
    branches:
      - development

jobs:
  test-and-lint:
    uses: ./.github/workflows/common-steps.yml

  additional-steps:
    needs: test-and-lint
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: |
          cd angular-bear
          npm test